const ADD_JOB = 'ADD_JOB';
const SET_JOBNAME = 'SET_JOBNAME';
const SET_LOADING = 'SET_LOADING';
const DELETE_JOB = 'DELETE_JOB';
const UPDATE_JOB = 'UPDATE_JOB';
const SET_EDITTODO = 'SET_EDITTODO';
const SET_NEWNAME = 'SET_NEWNAME';

export {ADD_JOB, SET_JOBNAME, SET_LOADING, DELETE_JOB, UPDATE_JOB, SET_EDITTODO, SET_NEWNAME}